before_script:
  - docker build -t eznode .

script: |
  bash -xeo << 'SHELL'
    shopt -s expand_aliases
    xpub=tpubD6NzVbkrYhZ4X9SErApTtvF833DCUydyjhVyWiciPXmqC6pzngB6EyhUnnqJvhXgJmHj3bkWdcSjkD4FsysLWsAZ1nJNdjV7CJfHBFu66C8

    docker run -d --name ez -v /etc/hosts:/ez/hosts eznode NETWORK=regtest XPUB=$xpub TOR=1 SSHD=1 SSL=1 SPECTER=1
    docker logs ez &
    alias ez='docker exec ez'

    curl ez:3060/stream &

    addr=$(curl -L ez:3060/wallet/ju9npsex/next | jq -r .address)
    ez bitcoin-cli -rpcwallet=miner sendtoaddress $addr 1.234

    sleep 3
    curl -v ez:3060/address/$addr/stats
    [ $(curl ez:3060/address/$addr/stats | tee /dev/stdout | jq -r .unconfirmed_balance) -eq 123400000 ]
SHELL
