#!/bin/bash
set -eo pipefail
source /ez/util.sh

bool_opt "$BWT" || abort_service
wait_for_bitcoind

# General config
export ELECTRUM_ADDR=$BIND_ADDR:50001
export HTTP_ADDR=$BIND_ADDR:3060
export NO_REQUIRE_ADDRESSES=1
export NOTIFY_FD=5
export RUST_LOG_STYLE=always

# Enable real-time updates using unix socket notifications when bitcoind is running locally.
# Also see init.sh and https://github.com/bwt-dev/bwt#real-time-indexing
if [ "$BITCOIND_MODE" == "local" ]; then
  mkdir -p /run/bwt && chown bwt /run/bwt
  export UNIX_LISTENER_PATH=/run/bwt/notify-socket
  export UNIX_LISTENER_MODE=511 # 777 in octal
  export POLL_INTERVAL=${POLL_INTERVAL:-90} # seconds
fi

# Disable historical rescan by default when pruning is enabled
if [ -n "$PRUNE" ] && [ "$PRUNE" != "0" ]; then
  export RESCAN_SINCE=${RESCAN_SINCE:-now}
fi

# Create a 'bwt' wallet by default
if [ -z "$BITCOIND_WALLET" ]; then
  export BITCOIND_WALLET=bwt
  export CREATE_WALLET_IF_MISSING=1
fi

# Suppress bwt's default startup banner and display it on our own,
# with a slight delay and some modifications
if [ -z "$NO_STARTUP_BANNER" ]; then
  export NO_STARTUP_BANNER=1
  mkdir /tmp/banner.once 2> /dev/null && (wait_for_service bwt 0 && sleep 1 && banner -s &)
fi

# Start
info bwt Starting Bitcoin Wallet Tracker...
exec s6-setuidgid bwt bwt $BWT_OPTS 2>&1
